### ISSUE TITLE
调用 dispose 方法不恢复容器内部原本的子元素

### ISSUE THREAD

**Issue by elewen** [apache/echarts#15200]
### Version
5.1.2

### Steps to reproduce
我有如下的模板，通过 echarts.init(this.$refs.chart) 将图表显示在div中，当还未init图表时容器显示了那段话（请点击...）这的确是我希望的。之后 调用 dispose 后希望重新显示那段话（请点击...），但实际情况是并没有显示那段话（请点击...）.

```html
<div style="width: 100%;height: 100%;display: flex;align-items: center;justify-content: center;" ref="chart" v-loading="loading">
    <span style="font-size: 14px;color: #aaa;">请点击下方表格中的具体SKU后查看对应图表</span>
  </div>
```

### What is expected?
调用 dispose 后希望重新显示容器中的 fallback 信息

### What is actually happening?
调用 dispose 后不会显示容器中的 fallback 信息

**Comment by plainheart** [comment]
ECharts 会将容器内元素全部清空，建议将 fallback 提示移至 echarts 容器外层，手动控制显示/隐藏，或者使用CSS `:empty` 选择器。如：

```css
.chart-box:empty::after {
    content: '请点击下方表格中的具体SKU后查看对应图表';
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 14px;
    color: #aaa;
}
```
