### ISSUE TITLE
v5.0+ Tooltip injected css won't respect 

### ISSUE THREAD

**Issue by urgrund** [apache/echarts#15831]
### Version
5.2.0

### Reproduction link
[https://jsfiddle.net/017mxbdz/1/](https://jsfiddle.net/017mxbdz/1/)

### Steps to reproduce
Example 1
Create a class that has a background color
```css
.test{
  background-color: 'blue';
}
```
set
```css  
backgroundColor  : 'rgba(255,0,0,1)'  ,
className: 'test',
```

in the tooltip: {}  object inside an option

Note that the red value comes through even with a custom class wanting a different color 
You need to go into F12 devtools and turn off the injected 'background-color' style to observe the custom CSS 
This holds true for any CSS that eCharts injects into the tooltip.  

Making it hard to have custom style.

A workaround is styling the content itself in the formatter: function(){}

BUT,  this has next issue...   
eCharts >5.0 injects 'will-change:transform'  which is breaking custom backdrop-filters (they are fantastic way to really personalize tooltips and have been using for 2yrs  with eCharts4) :)

eCharts 4.0 did not inject this property.

### What is expected?
- Custom provided CSS class should display as expected in a Tooltip
- CSS features such as backdropfilter should work as expected in a Tooltip

### What is actually happening?
- Custom class properties are being overwritten by eCharts CSS
- backdrop filters are broken with 'will-transform' injected CSS by eCharts

---
I have some images I can show for examples but unfortunately this issue reported doesn't have upload? 

Below is the injected CSS
```css
element.style {
    position: absolute;
    display: block;
    border-style: solid;
    white-space: nowrap;
    z-index: 9999999;
    will-change: unset;
    box-shadow: rgb(0 0 0 / 20%) 1px 2px 10px;
    background-color: rgba(0, 0, 0, 0);
    border-width: 1px;
    border-radius: 4px;
    color: rgb(102, 102, 102);
    font: 150 12px / 18px Poppins;
    padding: 10px;
    top: 0px;
    left: 0px;
    transform: translate3d(30px, -120px, 0px);
    border-color: rgb(255, 255, 0);
    pointer-events: none;
}
```
